import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Widget.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Widget() {
  return (
    <>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <div className={styles.widget}>
          <div className={styles.widgetHeader}>
            HEADER
          </div>
          <div className={styles.widgetBody}>
          <Image
                src="/bijgeloof/flowers/Flower5.jpeg"
                alt="Flower 5 Image"
                width={268}
                height={474}
                priority
              />
          </div>
          <div className={styles.widgetFooter}>
            <div className={styles.feed}>
            <Image
                src="/bijgeloof/1KiloOfOrganicWaste.jpeg"
                alt="1 Kilo Of Organic Waster"
                width={100}
                height={100}
                priority
              />
            </div>
            <div className={styles.foto}>
            <Image
                src="/bijgeloof/TakeAFoto.jpeg"
                alt="Take 2 Foto's"
                width={100}
                height={100}
                priority
              />
            </div>
            <div className={styles.water}>
            <Image
                src="/bijgeloof/10LitersWater.jpeg"
                alt="10 Liters of Water"
                width={100}
                height={100}
                priority
              />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
